// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdeRmYFeLY7EIzrONmhVmqCokYtVeXSxw',
    appId: '1:83790317968:web:dcb52989a7a5de3fc38b15',
    messagingSenderId: '83790317968',
    projectId: 'gotask-4ec65',
    authDomain: 'gotask-4ec65.firebaseapp.com',
    storageBucket: 'gotask-4ec65.appspot.com',
    measurementId: 'G-YX9TMFWWTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACkM6pn2V3ax7fCl_rU10tqukgvuT04f0',
    appId: '1:83790317968:android:7424862f510effd3c38b15',
    messagingSenderId: '83790317968',
    projectId: 'gotask-4ec65',
    storageBucket: 'gotask-4ec65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzX35W2bjAHyU11R7_M3XnwLSml88CoTs',
    appId: '1:83790317968:ios:af250b722b5b871fc38b15',
    messagingSenderId: '83790317968',
    projectId: 'gotask-4ec65',
    storageBucket: 'gotask-4ec65.appspot.com',
    androidClientId: '83790317968-0iu2hngg14q3plfjfor7brp8v1vqd8ot.apps.googleusercontent.com',
    iosClientId: '83790317968-c90ds5j6seh1hf6kp47undbt14bqltil.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzX35W2bjAHyU11R7_M3XnwLSml88CoTs',
    appId: '1:83790317968:ios:af250b722b5b871fc38b15',
    messagingSenderId: '83790317968',
    projectId: 'gotask-4ec65',
    storageBucket: 'gotask-4ec65.appspot.com',
    androidClientId: '83790317968-0iu2hngg14q3plfjfor7brp8v1vqd8ot.apps.googleusercontent.com',
    iosClientId: '83790317968-c90ds5j6seh1hf6kp47undbt14bqltil.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdeRmYFeLY7EIzrONmhVmqCokYtVeXSxw',
    appId: '1:83790317968:web:79354f28f04fbf7cc38b15',
    messagingSenderId: '83790317968',
    projectId: 'gotask-4ec65',
    authDomain: 'gotask-4ec65.firebaseapp.com',
    storageBucket: 'gotask-4ec65.appspot.com',
    measurementId: 'G-2845QHV3GH',
  );

}